### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [userjinha/CPP202309#4]
### 없는 파일
- challenge/week2/temperature.cpp 
- challenge/week2/temperature2.cpp 
- challenge/week3/menuif.cpp 
- project/week8/mud_game.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일:
- project/week6/tic_tac_toe.pdf
- project/week8/mud_game.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/countChar
    - Error: expected 'while' in do/while loop [line 37]
    - Error: expected '}' [line 38]
        - 중괄호가 맞지 않습니다. 코드에 중괄호를 추가해주세요.
- ERROR in challenge/week3/guessNum
    - Error: expected 'while' in do/while loop [line 37]
    - Error: expected '}' [line 37]
        - 중괄호가 맞지 않습니다. 코드에 중괄호를 추가해주세요.
- ERROR in project/week6/tic_tac_toe
    - Error: use of undeclared identifier 'currnetUser' [line 98]
         - currnetUser는 없는 변수입니다. 해당 라인에 오타를 수정해주세요.
    - Error: expected '}' [line 115]
        - 중괄호가 맞지 않습니다. 코드에 중괄호를 추가해주세요.

**Comment by userjinha** [comment]
모두 수정하고 커밋 했습니다.
